version: "3"
volumes:
  postgres-data:
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
      - PUBLISHABLE_KEY=pk_test_kpXTWLmBQ2J0UnfJ5WoW0diB00Cb1dKrFS
      - SECRET_KEY=sk_test_eQIXS8VQQ0ADpjr46GDKk40c00jitq3paH
    command: bash -c "rm -f tmp/pids/server.pid  && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes:
    #   - .:/project # Only mount this volume if running Rails in development mode.
    ports:
      - "3000:3000"
    depends_on:
      - db
    # restart: always
